-- Oracle 10g Initialization Script for Inventory Pro

-- 1. Drop existing tables (if re-running)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE inventory_transactions CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE locations CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE warehouses CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE otps CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 2. Create Tables

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'Staff',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE otps (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(150) NOT NULL,
    otp_code VARCHAR2(10) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    code VARCHAR2(50) UNIQUE NOT NULL,
    location_desc VARCHAR2(200),
    capacity NUMBER DEFAULT 500,
    status VARCHAR2(20) DEFAULT 'active'
);

CREATE TABLE locations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id NUMBER NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
    name VARCHAR2(100) NOT NULL,
    label VARCHAR2(50) NOT NULL,
    type VARCHAR2(50),
    zone VARCHAR2(50),
    fill_percentage NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'healthy'
);

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    sku VARCHAR2(100) UNIQUE NOT NULL,
    category VARCHAR2(100),
    uom VARCHAR2(20),
    on_hand NUMBER DEFAULT 0,
    reorder_point NUMBER DEFAULT 0,
    reorder_qty NUMBER DEFAULT 0,
    location_id NUMBER REFERENCES locations(id) ON DELETE SET NULL,
    avg_daily_usage NUMBER DEFAULT 0, -- For predictive reordering
    lead_time_days NUMBER DEFAULT 7,  -- For predictive reordering
    status VARCHAR2(50) DEFAULT 'In Stock'
);

CREATE TABLE inventory_transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    trans_type VARCHAR2(50) NOT NULL, -- receipt, delivery, transfer, adjustment
    reference VARCHAR2(100),
    product_id NUMBER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    qty_change NUMBER NOT NULL,
    from_loc VARCHAR2(100),
    to_loc VARCHAR2(100),
    note VARCHAR2(500)
);

-- 3. Insert Demo Data

INSERT INTO users (name, email, password_hash, role) 
VALUES ('sneha', 'pepperchilli4321@gmail.com', '1234', 'Administrator');

INSERT INTO warehouses (name, code, location_desc) 
VALUES ('Warehouse A', 'WH-A', 'Main Hub');

INSERT INTO locations (warehouse_id, name, label, type, zone) 
VALUES (1, 'WH-A/Stock/A1', 'A1', 'General', 'A');

INSERT INTO products (name, sku, category, uom, on_hand, reorder_point, avg_daily_usage, lead_time_days, location_id)
VALUES ('Steel Rod 12mm', 'SR-12-001', 'Construction', 'Unit', 1240, 100, 15, 7, 1);

INSERT INTO products (name, sku, category, uom, on_hand, reorder_point, avg_daily_usage, lead_time_days, location_id)
VALUES ('Copper Wire (1m)', 'CW-01-992', 'Electronics', 'Meter', 42, 100, 12, 5, 1);

INSERT INTO products (name, sku, category, uom, on_hand, reorder_point, avg_daily_usage, lead_time_days, location_id)
VALUES ('Motion Sensor', 'MS-99-007', 'Electronics', 'Unit', 3, 20, 2, 14, 1);

-- Generate some historical transactions for the Heatmap / Timeline
INSERT INTO inventory_transactions (trans_type, reference, product_id, qty_change, to_loc, note)
VALUES ('receipt', 'REC-001', 1, 1500, 'WH-A/Stock/A1', 'Initial Stock');

INSERT INTO inventory_transactions (trans_type, reference, product_id, qty_change, from_loc, to_loc, note)
VALUES ('delivery', 'DEL-001', 1, -260, 'WH-A/Stock/A1', 'Customer X', 'Bulk sale');

COMMIT;
